In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import AUC

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score, hamming_loss
import re
import string


In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
path1="/content/drive/MyDrive/DeepLearning/Tags.csv"
df_t=pd.read_csv(path1)
path2="/content/drive/MyDrive/Questions.csv"
df_q1=pd.read_csv(path2, nrows=105000)

In [ ]:
list(df_t.columns)

['Id', 'Tag']

In [ ]:
tags1 = df_t.Tag.value_counts()
top_10_tags = tags1[0:10]
top_10_tags[0:10]

Tag
javascript    124155
java          115212
c#            101186
php            98808
android        90659
jquery         78542
python         64601
html           58976
c++            47591
ios            47009
Name: count, dtype: int64

In [ ]:
tags = {'Tag': ['javascript','java','c#','php','android','jquery','python','html','c++','ios']}

In [ ]:
top_10_tags = pd.DataFrame(tags)
top_10_tags

Tag
0  javascript
1        java
2          c#
3         php
4     android
5      jquery
6      python
7        html
8         c++
9         ios

In [ ]:
def search_string(s,search):
  return search in str(s).lower()

In [ ]:
mask1 = df_q1.apply(lambda x: x.map(lambda s: search_string(s, 'javascript')))
mask2 = df_q1.apply(lambda x: x.map(lambda s: search_string(s, 'java')))
mask3 = df_q1.apply(lambda x: x.map(lambda s: search_string(s, 'c#')))
mask4 = df_q1.apply(lambda x: x.map(lambda s: search_string(s, 'php')))
mask5 = df_q1.apply(lambda x: x.map(lambda s: search_string(s, 'android')))
mask6 = df_q1.apply(lambda x: x.map(lambda s: search_string(s, 'jquery')))
mask7 = df_q1.apply(lambda x: x.map(lambda s: search_string(s, 'python')))
mask8 = df_q1.apply(lambda x: x.map(lambda s: search_string(s, 'html')))
mask9 = df_q1.apply(lambda x: x.map(lambda s: search_string(s, 'c++')))
mask10 = df_q1.apply(lambda x: x.map(lambda s: search_string(s, 'ios')))

In [ ]:
filtered_df1_q1 = df_q1.loc[mask1.any(axis=1)]
filtered_df2_q1 = df_q1.loc[mask2.any(axis=1)]
filtered_df3_q1 = df_q1.loc[mask3.any(axis=1)]
filtered_df4_q1 = df_q1.loc[mask4.any(axis=1)]
filtered_df5_q1 = df_q1.loc[mask5.any(axis=1)]
filtered_df6_q1 = df_q1.loc[mask6.any(axis=1)]
filtered_df7_q1 = df_q1.loc[mask7.any(axis=1)]
filtered_df8_q1 = df_q1.loc[mask8.any(axis=1)]
filtered_df9_q1 = df_q1.loc[mask9.any(axis=1)]
filtered_df10_q1 = df_q1.loc[mask10.any(axis=1)]

In [ ]:
final_df1_q1 = pd.concat([filtered_df1_q1['Title'],filtered_df1_q1['Body']],axis=1)
final_df2_q1 = pd.concat([filtered_df2_q1['Title'],filtered_df2_q1['Body']],axis=1)
final_df3_q1 = pd.concat([filtered_df3_q1['Title'],filtered_df3_q1['Body']],axis=1)
final_df4_q1 = pd.concat([filtered_df4_q1['Title'],filtered_df4_q1['Body']],axis=1)
final_df5_q1 = pd.concat([filtered_df5_q1['Title'],filtered_df5_q1['Body']],axis=1)
final_df6_q1 = pd.concat([filtered_df6_q1['Title'],filtered_df6_q1['Body']],axis=1)
final_df7_q1 = pd.concat([filtered_df7_q1['Title'],filtered_df7_q1['Body']],axis=1)
final_df8_q1 = pd.concat([filtered_df8_q1['Title'],filtered_df8_q1['Body']],axis=1)
final_df9_q1 = pd.concat([filtered_df9_q1['Title'],filtered_df9_q1['Body']],axis=1)
final_df10_q1 = pd.concat([filtered_df10_q1['Title'],filtered_df10_q1['Body']],axis=1)
# Assigning 1 to appropriate Tag columns
final_df1_q1['javascript'] = 1
final_df2_q1['java'] = 1
final_df3_q1['c#'] = 1
final_df4_q1['php'] = 1
final_df5_q1['android'] = 1
final_df6_q1['jquery'] = 1
final_df7_q1['python'] = 1
final_df8_q1['html'] = 1
final_df9_q1['c++'] = 1
final_df10_q1['ios'] = 1

In [ ]:
#Merging Rows of different Tags into single data frame
rows_tag_merge = pd.concat([final_df1_q1,final_df2_q1,final_df3_q1,final_df4_q1,final_df5_q1,final_df6_q1,final_df7_q1,final_df8_q1,final_df9_q1,final_df10_q1], axis=0)

In [ ]:
#Creating columns for each Tag.
final_data = pd.DataFrame()
final_data['Title'] = rows_tag_merge.loc[:,'Title']
final_data['Body'] = rows_tag_merge.loc[:,'Body']
final_data['javascript'] = rows_tag_merge.loc[:,'javascript']
final_data['java'] = rows_tag_merge.loc[:,'java']
final_data['c#'] = rows_tag_merge.loc[:,'c#']
final_data['php'] = rows_tag_merge.loc[:,'php']
final_data['android'] = rows_tag_merge.loc[:,'android']
final_data['jquery'] = rows_tag_merge.loc[:,'jquery']
final_data['python'] = rows_tag_merge.loc[:,'python']
final_data['html'] = rows_tag_merge.loc[:,'html']
final_data['c++'] = rows_tag_merge.loc[:,'c++']
final_data['ios'] = rows_tag_merge.loc[:,'ios']

In [ ]:
#NaN values of tags are assigned to 0
final_data_complete = final_data.fillna(0)

In [ ]:
#Preprocess the text (basic cleaning)
def preprocess_text(text):
    # Remove punctuation and lowercase everything
    text = text.lower()
    text = re.sub(f"[{string.punctuation}]", "", text)
    return text

In [ ]:
final_data_complete['Cleaned_Body'] = final_data_complete['Body'].apply(preprocess_text)
final_data_complete['Cleaned_Title'] = final_data_complete['Title'].apply(preprocess_text)

In [ ]:
X_data = pd.DataFrame()
X_data['Title_Body'] = final_data_complete['Cleaned_Body'] +  final_data_complete['Cleaned_Title']

In [ ]:
X_data

Title_Body
35      pmy dad called me today and said people going ...
51      phow is it possible to make prototype methods ...
79      precently i have been having issues with firef...
118     pi have an ajaxnet enabled aspnet 20 web site ...
161     pwhat are some standard practices for managing...
...                                                   ...
104855  pi tried the code below to run a standalone ut...
104876  pi have two classes person and student im curr...
104896  pi just released my new app ibeat which worked...
104902  pi have a class setup and from that class i am...
104910  pi am trying to write a python script to do a ...

[60917 rows x 1 columns]

In [ ]:
y = final_data_complete[['javascript','java', 'c#', 'php', 'android', 'jquery', 'python', 'html', 'c++', 'ios']].astype(int)

In [ ]:
y

javascript  java  c#  php  android  jquery  python  html  c++  ios
35               1     0   0    0        0       0       0     0    0    0
51               1     0   0    0        0       0       0     0    0    0
79               1     0   0    0        0       0       0     0    0    0
118              1     0   0    0        0       0       0     0    0    0
161              1     0   0    0        0       0       0     0    0    0
...            ...   ...  ..  ...      ...     ...     ...   ...  ...  ...
104855           0     0   0    0        0       0       0     0    0    1
104876           0     0   0    0        0       0       0     0    0    1
104896           0     0   0    0        0       0       0     0    0    1
104902           0     0   0    0        0       0       0     0    0    1
104910           0     0   0    0        0       0       0     0    0    1

[60917 rows x 10 columns]

In [ ]:
vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(X_data['Title_Body'])

In [ ]:
print (X)

  (0, 283813)	0.006577486310208358
  (0, 95624)	0.016729236954814805
  (0, 53337)	0.007125615811731126
  (0, 385603)	0.010922533707623552
  (0, 330818)	0.009925586558565194
  (0, 278114)	0.008649012498327531
  (0, 144337)	0.007545182423377091
  (0, 408365)	0.02395944212442112
  (0, 142662)	0.01350879251692746
  (0, 8448)	0.015850660098551423
  (0, 405480)	0.018504149435378585
  (0, 388945)	0.005162398563266443
  (0, 110661)	0.009620855014475932
  (0, 83263)	0.012389996221826762
  (0, 192103)	0.015688547854236366
  (0, 372825)	0.012896929380505252
  (0, 51175)	0.009342857517780837
  (0, 377235)	0.015060797140782674
  (0, 414724)	0.013505810865542955
  (0, 113900)	0.013982492121704696
  (0, 280863)	0.00836463206187763
  (0, 284884)	0.01498282276306663
  (0, 344836)	0.021763663627200773
  (0, 261996)	0.0074084022890847975
  (0, 404874)	0.013053149020505176
  :	:
  (60916, 299323)	0.07627279755477881
  (60916, 373864)	0.0669943793895975
  (60916, 309130)	0.07424388911346469
  (60916, 24270

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
print(y_train)

        javascript  java  c#  php  android  jquery  python  html  c++  ios
103874           0     0   0    0        0       0       0     1    0    0
74917            0     0   0    0        0       0       0     1    0    0
57347            0     0   1    0        0       0       0     0    0    0
101618           0     0   0    1        0       0       0     0    0    0
85113            0     0   0    0        1       0       0     0    0    0
...            ...   ...  ..  ...      ...     ...     ...   ...  ...  ...
92363            0     0   0    0        0       0       0     1    0    0
47911            0     0   0    0        0       1       0     0    0    0
17622            1     0   0    0        0       0       0     0    0    0
80746            0     1   0    0        0       0       0     0    0    0
18027            0     0   0    0        0       0       0     0    1    0

[48733 rows x 10 columns]


In [ ]:
from sklearn.multioutput import MultiOutputClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
classifier = MultiOutputClassifier(LogisticRegression())

In [ ]:
classifier.fit(X_train, y_train)

MultiOutputClassifier(estimator=LogisticRegression())

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
print(y_pred)

[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
#y_test_temp = y_test.to_numpy()
#for i in range(X_test.shape[0]):
#  print(y_test_temp[i],y_pred[i])

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.255252790544977
Classification Report:
               precision    recall  f1-score   support

           0       0.27      0.06      0.10      1150
           1       0.69      0.30      0.42      2617
           2       0.76      0.26      0.38      1313
           3       0.75      0.41      0.53      1659
           4       0.81      0.55      0.65       471
           5       0.57      0.27      0.37      1089
           6       0.78      0.44      0.56       746
           7       0.57      0.18      0.27      2086
           8       0.63      0.17      0.26       786
           9       0.70      0.10      0.17       267

   micro avg       0.67      0.27      0.38     12184
   macro avg       0.65      0.27      0.37     12184
weighted avg       0.64      0.27      0.37     12184
 samples avg       0.26      0.27      0.27     12184



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
import joblib

In [ ]:
joblib.dump(classifier, 'Multiclass_Multilabel_prediction.joblib')

['Multiclass_Multilabel_prediction.joblib']

In [ ]:
from google.colab import files

In [ ]:
files.download('Multiclass_Multilabel_prediction.joblib')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>